language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
#  - hhvm
#  - hhvm-nightly

services:
  - mysql

#before_install:
#  - pear channel-discover pear.phing.info
#  - pear install phing/phing
#  - phpenv rehash

install:
  - cd .. && git clone https://github.com/yiisoft/yii.git yii
  - cd yii && git checkout 1.1.17
  - cd ../argilla
  - wget http://www.phing.info/get/phing-latest.phar
  - chmod +x phing-latest.phar
  - sudo mv phing-latest.phar phing.phar

before_script:
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'prog'@'localhost' IDENTIFIED BY '123' WITH GRANT OPTION;" -uroot
  - php phing.phar bootstrap -DdbName=argilla -DdbTablePrefix=argilla_ -DdbUser=prog -DdbPassword=123 -Dconfirm=y -DconfirmTest=y

script:
  - phpunit -c backend/protected/tests/phpunit.xml backend/protected/tests/unit/
  - phpunit -c protected/tests/phpunit.xml protected/tests/unit/